'use strict';
/* CoC 7th 疯狂症状表（本模块为独立实现，条目按规则书分类自行撰写）。
 *
 *   TEMP_INSANITY / LONG_INSANITY  按 1d10 取用「疯狂发作」结果（临时 / 长期）
 *   FEAR / MANIA                   按 1d100 取用的恐惧症 / 躁狂症条目
 * 各表索引 0 留空，便于直接用骰值取值。
 * 占位符：{pc} 角色名、{dur} 持续时长、{detail} 具体症状、{detail_roll} 具体症状骰点、{nick} 昵称。 */

/* ── 疯狂发作·临时（1d10 轮）── */
const TEMP_INSANITY = [
  '',
  '失忆：{pc}对刚刚的经历出现记忆空白，只记得最后身处的安全地点，中间发生了什么一片空白，持续{dur}轮。',
  '假性残疾：{pc}出现心理性的失明、失聪或某处肢体失去知觉与力量，医学检查却查不出病因，持续{dur}轮。',
  '暴力倾向：{pc}被突如其来的怒火与破坏欲吞没，对周围不分敌友地打砸攻击，持续{dur}轮。',
  '偏执：{pc}坚信有人在暗中监视自己、身边同伴随时可能背叛，拒绝任何信任与帮助，持续{dur}轮。',
  '人际依赖：{pc}把身边的某个人错认成自己至关重要之人，并执意与对方维持那种关系，持续{dur}轮。',
  '昏厥：{pc}当场失去意识倒地，昏迷{dur}轮后才醒来。',
  '逃避行为：{pc}只想立刻离开当前所在之处，不择手段地夺路而逃，持续{dur}轮。',
  '歇斯底里：{pc}陷入失控的极端情绪，或狂笑、或痛哭、或尖叫、或剧烈颤抖，持续{dur}轮。',
  '恐惧：{pc}毫无来由地陷入强烈的恐惧，即使恐惧对象并不真实存在，持续{dur}轮。\n{detail_roll}\n具体恐惧症：{detail}（KP 也可从恐惧症状表中另行指定）',
  '躁狂：{pc}因某个诱因进入躁狂状态，行为亢奋而失控，持续{dur}轮。\n{detail_roll}\n具体躁狂症：{detail}（KP 也可从躁狂症状表中另行指定）'
];

/* ── 疯狂发作·长期（1d10 小时）── */
const LONG_INSANITY = [
  '',
  '失忆：{dur}小时后{pc}回过神来，发现自己身处陌生之地，连自己是谁都想不起来，记忆会随时间慢慢恢复。',
  '被窃：{dur}小时后{pc}恢复清醒，发现自己遭窃，财物尽失，但身体毫发无损。',
  '遍体鳞伤：{dur}小时后{pc}恢复清醒，发现自己满身拳痕与瘀伤，生命值降至发疯前的一半（不构成重伤），并未遭窃；具体缘由由 KP 决定。',
  '暴力倾向：{pc}陷入强烈的暴力与破坏冲动，持续{dur}小时。',
  '极端信念：在接下来的{dur}小时里，{pc}会以极端而疯狂的方式践行自己的某一信念。',
  '重要之人：{dur}小时内，{pc}会不顾一切地奔向对自己至关重要的那个人，并为这段关系采取行动。',
  '被收容：{dur}小时后，{pc}在精神病院的病房、或是警局的拘留室里回过神来。',
  '逃避行为：{dur}小时后{pc}恢复清醒，发现自己已身处很远的地方。',
  '恐惧：{pc}新患上一项恐惧症，在{dur}小时内将竭力回避恐惧源，之后才逐渐平复。\n{detail_roll}\n具体恐惧症：{detail}（KP 也可从恐惧症状表中另行指定）',
  '躁狂：{pc}新患上一项躁狂症，在{dur}小时内完全沉浸其中，之后才恢复理智；他人是否能够理解，取决于 KP 与{nick}。\n{detail_roll}\n具体躁狂症：{detail}（KP 也可从躁狂症状表中另行指定）'
];

/* ── 恐惧症（1d100）── */
const FEAR = [
  '',
  '洗澡恐惧症（Ablutophobia）：害怕洗澡、淋浴或一切与清洗有关的场景。',
  '恐高症（Acrophobia）：害怕身处高处，越空旷越高越难忍受。',
  '飞行恐惧症（Aerophobia）：害怕乘坐飞机或任何腾空飞行。',
  '广场恐惧症（Agoraphobia）：害怕开阔或人群密集的公共场所，总想尽快逃离。',
  '恐鸡症（Alektorophobia）：害怕鸡，连羽毛与叫声也会引起不适。',
  '大蒜恐惧症（Alliumphobia）：害怕大蒜及其气味。',
  '乘车恐惧症（Amaxophobia）：害怕乘坐马车、汽车等地面载具。',
  '恐风症（Ancraophobia）：害怕风吹过身体的感觉，尤其是狂风。',
  '男性恐惧症（Androphobia）：害怕成年男性。',
  '恐英症（Anglophobia）：害怕英格兰或一切与英格兰文化相关的事物。',
  '恐花症（Anthophobia）：害怕花朵，哪怕是图案或香气。',
  '截肢者恐惧症（Apotemnophobia）：害怕肢体残缺的人。',
  '蜘蛛恐惧症（Arachnophobia）：害怕蜘蛛。',
  '闪电恐惧症（Astraphobia）：害怕闪电与随之而来的雷鸣。',
  '废墟恐惧症（Atephobia）：害怕残垣断壁与荒废破败的场所。',
  '长笛恐惧症（Aulophobia）：害怕长笛及其吹奏声。',
  '细菌恐惧症（Bacteriophobia）：害怕细菌、病菌与一切看不见的污染。',
  '弹道恐惧症（Ballistophobia）：害怕子弹、导弹等飞行投射物。',
  '跌倒恐惧症（Basophobia）：害怕站立或行走时失去平衡、摔倒在地。',
  '书籍恐惧症（Bibliophobia）：害怕书籍与阅读。',
  '植物恐惧症（Botanophobia）：害怕植物，尤其是茂密生长的草木。',
  '美女恐惧症（Caligynephobia）：害怕美貌的女性。',
  '寒冷恐惧症（Cheimaphobia）：害怕寒冷与被冻伤。',
  '钟表恐惧症（Chronomentrophobia）：害怕钟表，也害怕时间的流逝。',
  '幽闭恐惧症（Claustrophobia）：害怕身处狭窄封闭的空间。',
  '小丑恐惧症（Coulrophobia）：害怕小丑及其夸张的妆容。',
  '恐犬症（Cynophobia）：害怕狗及其吠叫。',
  '恶魔恐惧症（Demonophobia）：害怕邪灵与恶魔。',
  '人群恐惧症（Demophobia）：害怕拥挤的人群。',
  '牙科恐惧症（Dentophobia）：害怕牙医与一切牙科治疗。',
  '弃物恐惧症（Disposophobia）：害怕丢弃物品，习惯性地囤积一切。',
  '皮毛恐惧症（Doraphobia）：害怕动物的毛皮。',
  '过街恐惧症（Dromophobia）：害怕穿过马路或横越开阔路面。',
  '教堂恐惧症（Ecclesiophobia）：害怕教堂与宗教场所。',
  '镜子恐惧症（Eisoptrophobia）：害怕镜子，也害怕看见自己的倒影。',
  '针尖恐惧症（Enetophobia）：害怕针与大头针。',
  '昆虫恐惧症（Entomophobia）：害怕昆虫。',
  '恐猫症（Felinophobia）：害怕猫。',
  '过桥恐惧症（Gephyrophobia）：害怕过桥，尤其是悬空或狭窄的桥。',
  '恐老症（Gerontophobia）：害怕老年人，也害怕自己变老。',
  '恐女症（Gynophobia）：害怕女性。',
  '恐血症（Haemaphobia）：害怕血，哪怕只是少量。',
  '罪孽恐惧症（Hamartophobia）：害怕自己犯下罪孽或做出亵渎之事。',
  '触摸恐惧症（Haphophobia）：害怕被他人触碰。',
  '爬虫恐惧症（Herpetophobia）：害怕蛇、蜥蜴等爬行动物。',
  '迷雾恐惧症（Homichlophobia）：害怕浓雾与能见度极低的天气。',
  '火器恐惧症（Hoplophobia）：害怕枪械等火器。',
  '恐水症（Hydrophobia）：害怕水，尤其是深水与溺水。',
  '睡眠恐惧症（Hypnophobia）：害怕入睡，也害怕被催眠。',
  '医生恐惧症（Iatrophobia）：害怕医生与医疗场所。',
  '鱼类恐惧症（Ichthyophobia）：害怕鱼。',
  '蟑螂恐惧症（Katsaridaphobia）：害怕蟑螂。',
  '雷鸣恐惧症（Keraunophobia）：害怕雷声。',
  '蔬菜恐惧症（Lachanophobia）：害怕蔬菜。',
  '噪音恐惧症（Ligyrophobia）：害怕突如其来的刺耳噪音。',
  '湖泊恐惧症（Limnophobia）：害怕湖泊与平静的大片水面。',
  '机械恐惧症（Mechanophobia）：害怕机器与机械装置。',
  '巨物恐惧症（Megalophobia）：害怕过于庞大的物体。',
  '束缚恐惧症（Merinthophobia）：害怕被捆绑或受到束缚。',
  '流星恐惧症（Meteorophobia）：害怕流星、陨石与天降之物。',
  '孤独恐惧症（Monophobia）：害怕独自一人。',
  '污秽恐惧症（Mysophobia）：害怕污垢、灰尘与不洁之物。',
  '黏液恐惧症（Myxophobia）：害怕黏液、软泥之类的黏稠物体。',
  '尸体恐惧症（Necrophobia）：害怕尸体与死者的遗骸。',
  '数字八恐惧症（Octophobia）：害怕数字 8。',
  '牙齿恐惧症（Odontophobia）：害怕牙齿，也害怕看牙。',
  '梦境恐惧症（Oneirophobia）：害怕做梦与梦中的内容。',
  '称呼恐惧症（Onomatophobia）：害怕听到某个特定的词或名字。',
  '恐蛇症（Ophidiophobia）：害怕蛇。',
  '恐鸟症（Ornithophobia）：害怕鸟，尤其是成群或扑翅的鸟。',
  '寄生虫恐惧症（Parasitophobia）：害怕寄生虫与寄生生物。',
  '人偶恐惧症（Pediophobia）：害怕人偶、玩偶与木偶。',
  '吞咽恐惧症（Phagophobia）：害怕吞咽，也害怕被吞下。',
  '药物恐惧症（Pharmacophobia）：害怕服药与药物。',
  '鬼魂恐惧症（Phasmophobia）：害怕鬼魂与幽灵。',
  '日光恐惧症（Phenogophobia）：害怕日光与明亮的天光。',
  '胡须恐惧症（Pogonophobia）：害怕胡须。',
  '河流恐惧症（Potamophobia）：害怕河流与湍急的水流。',
  '酒精恐惧症（Potophobia）：害怕酒与含酒精的饮品。',
  '火焰恐惧症（Pyrophobia）：害怕火与火灾。',
  '魔法恐惧症（Rhabdophobia）：害怕魔法与超自然之力。',
  '黑暗恐惧症（Scotophobia）：害怕黑暗与夜晚。',
  '月亮恐惧症（Selenophobia）：害怕月亮。',
  '火车恐惧症（Siderodromophobia）：害怕乘坐火车出行。',
  '星辰恐惧症（Siderophobia）：害怕星星与夜空。',
  '狭窄恐惧症（Stenophobia）：害怕狭小的物件或逼仄的地方。',
  '对称恐惧症（Symmetrophobia）：害怕完全对称的事物。',
  '活埋恐惧症（Taphephobia）：害怕被活埋，也害怕墓地。',
  '公牛恐惧症（Taurophobia）：害怕公牛。',
  '电话恐惧症（Telephonophobia）：害怕接打电话。',
  '怪物恐惧症（Teratophobia）：害怕怪物与畸形的生物。',
  '海洋恐惧症（Thalassophobia）：害怕大海与深不可测的水域。',
  '手术恐惧症（Tomophobia）：害怕外科手术。',
  '数字十三恐惧症（Triskadekaphobia）：害怕数字 13。',
  '衣物恐惧症（Vestiphobia）：害怕衣物。',
  '女巫恐惧症（Wiccaphobia）：害怕女巫与巫术。',
  '黄色恐惧症（Xanthophobia）：害怕黄色，或害怕「黄」这个字。',
  '外语恐惧症（Xenoglossophobia）：害怕陌生语言与听不懂的话语。',
  '异域恐惧症（Xenophobia）：害怕陌生人、外地人与异国事物。',
  '动物恐惧症（Zoophobia）：害怕动物。'
];

/* ── 躁狂症（1d100）── */
const MANIA = [
  '',
  '沐浴癖（Ablutomania）：无法克制地反复清洗自己。',
  '犹豫癖（Aboulomania）：在哪怕最小的选择上也病态地迟疑不决。',
  '喜暗狂（Achluomania）：对黑暗怀着反常的迷恋，总想待在无光之处。',
  '喜高狂（Acromania）：痴迷于登高，总想爬上最高处。',
  '亲切癖（Agathomania）：病态地对任何人都过分友善热心。',
  '喜旷症（Agromania）：强烈地渴望待在开阔的原野与空地。',
  '喜尖狂（Aichmomania）：痴迷于尖锐锋利的器物。',
  '恋猫狂（Ailuromania）：对猫近乎病态地亲近。',
  '疼痛癖（Algomania）：痴迷于疼痛，甚至主动寻求痛感。',
  '喜蒜狂（Alliomania）：痴迷于大蒜，凡事都想添上蒜味。',
  '乘车癖（Amaxomania）：痴迷于乘车出行，闲不下来。',
  '欣快癖（Amenomania）：毫无缘由地持续感到亢奋喜悦。',
  '喜花狂（Anthomania）：痴迷于花朵，见花就要采撷或收集。',
  '计算癖（Arithmomania）：狂热地数数，凡物都要清点一遍。',
  '消费癖（Asoticamania）：鲁莽冲动地挥霍钱财。',
  '隐居癖（Automania）：过分地热爱独处，拒绝一切社交。',
  '芭蕾癖（Balletmania）：痴迷于芭蕾舞。',
  '窃书癖（Biliokleptomania）：无法克制偷书的冲动。',
  '恋书狂（Bibliomania）：痴迷于书籍与阅读，废寝忘食。',
  '磨牙癖（Bruxomania）：无法克制地磨牙。',
  '灵臆症（Cacodemomania）：病态地坚信自己被邪恶的灵体占据。',
  '美貌狂（Callomania）：痴迷于自己的容貌，反复端详修饰。',
  '地图狂（Cartacoethes）：随时随地都忍不住要看地图。',
  '跳跃狂（Catapedamania）：痴迷于从高处一跃而下。',
  '喜冷症（Cheimatomania）：反常地喜爱寒冷与冰冷的物体。',
  '舞蹈狂（Choreomania）：无法自控地不停起舞、抖动。',
  '恋床癖（Clinomania）：过分地贪恋躺在床上的时光。',
  '恋墓狂（Coimetromania）：痴迷于墓地，常去徘徊。',
  '色彩狂（Coloromania）：痴迷于某一种颜色，满眼都是它。',
  '小丑狂（Coulromania）：痴迷于小丑。',
  '恐惧狂（Countermania）：执着于反复经历恐怖的场面。',
  '杀戮癖（Dacnomania）：痴迷于杀戮。',
  '魔臆症（Demonomania）：病态地坚信自己被恶魔附身。',
  '抓挠癖（Dermatillomania）：执着于抓挠自己的皮肤。',
  '正义狂（Dikemania）：痴迷于目睹正义得到伸张。',
  '嗜酒狂（Dipsomania）：反常地渴求酒精。',
  '毛皮狂（Doramania）：痴迷于收集或穿戴毛皮。',
  '赠物癖（Doromania）：痴迷于向他人赠送礼物。',
  '漂泊症（Drapetomania）：执着于逃离当下，总想一走了之。',
  '漫游癖（Ecdemiomania）：执着于四处漫游，停不下来。',
  '自恋狂（Egomania）：近乎病态地以自我为中心、自我崇拜。',
  '职业狂（Empleomania）：对工作有持续而病态的渴求。',
  '臆罪症（Enosimania）：病态地坚信自己身负罪孽。',
  '学识狂（Epistemomania）：痴迷于获取知识与见闻。',
  '静止癖（Eremiomania）：执着于保持安静、一动不动。',
  '乙醚上瘾（Etheromania）：渴求乙醚等挥发性药剂。',
  '求婚狂（Gamomania）：痴迷于向人做出离奇的求婚。',
  '狂笑癖（Geliomania）：无法自制地强迫性大笑。',
  '巫术狂（Goetomania）：痴迷于女巫与巫术。',
  '写作癖（Graphomania）：痴迷于把每一件事都写下来。',
  '裸体狂（Gymnomania）：执着于袒露身体。',
  '妄想狂（Habromania）：不顾现实地充满愉悦的妄想。',
  '蠕虫狂（Helminthomania）：过分地喜爱蠕虫。',
  '枪械狂（Hoplomania）：痴迷于火器枪械。',
  '饮水狂（Hydromania）：反常地渴求饮水。',
  '喜鱼癖（Ichthyomania）：痴迷于鱼类。',
  '图标狂（Iconomania）：痴迷于图标与肖像。',
  '偶像狂（Idolomania）：痴迷于某个偶像，乃至愿意为其献身。',
  '信息狂（Infomania）：痴迷于搜集各种信息与资讯。',
  '射击狂（Klazomania）：反常地执着于射击。',
  '偷窃癖（Kleptomania）：反常地执着于偷窃。',
  '噪音癖（Ligyromania）：无法自制地制造响亮刺耳的噪音。',
  '喜线癖（Linonomania）：痴迷于线绳。',
  '彩票狂（Lotterymania）：极端执着于购买彩票。',
  '抑郁癖（Lypemania）：近乎病态地长期陷入抑郁低落。',
  '巨石狂（Megalithomania）：站在石环或立起的巨石旁时，会近乎病态地涌出古怪的创作冲动。',
  '旋律狂（Melomania）：痴迷于音乐或某段特定的旋律。',
  '作诗癖（Metromania）：无法抑制地想要不停作诗。',
  '憎恨癖（Misomania）：憎恨一切，或痴迷于憎恨某个对象。',
  '偏执狂（Monomania）：近乎病态地执着于某个念头或想法。',
  '夸大癖（Mythomania）：以近乎病态的程度说谎或夸大其词。',
  '臆想症（Nosomania）：妄想自己正被某种臆想出来的疾病折磨。',
  '记录癖（Notomania）：执着于记录一切，比如随身拍照。',
  '恋名狂（Onomamania）：痴迷于各种名字——人名、地名、物名。',
  '称名癖（Onomatomania）：无法抑制地反复念诵某个词。',
  '剔指癖（Onychotillomania）：执着于剔指甲。',
  '恋食癖（Opsomania）：对某种食物病态地热爱。',
  '抱怨癖（Paramania）：在抱怨中获得近乎病态的愉悦。',
  '面具狂（Personamania）：执着于佩戴面具。',
  '幽灵狂（Phasmomania）：痴迷于幽灵。',
  '谋杀癖（Phonomania）：病态地倾向谋杀。',
  '渴光癖（Photomania）：对光有病态的渴求。',
  '背德癖（Planomania）：病态地渴求违背社会道德。',
  '求财癖（Plutomania）：对财富有强迫性的渴望。',
  '欺骗狂（Pseudomania）：无法抑制地执着于撒谎。',
  '纵火狂（Pyromania）：执着于纵火。',
  '提问癖（Question-asking Mania）：执着于不停向人发问。',
  '挖鼻癖（Rhinotillexomania）：执着于挖鼻子。',
  '涂鸦癖（Scribbleomania）：沉迷于随手涂鸦。',
  '列车狂（Siderodromomania）：认为火车等轨道旅行有种病态的魅力。',
  '臆智症（Sophomania）：臆想自己拥有难以置信的智慧。',
  '科技狂（Technomania）：痴迷于新兴科技。',
  '臆咒狂（Thanatomania）：坚信自己已被某种死亡魔法诅咒。',
  '臆神狂（Theomania）：坚信自己是一位神灵。',
  '抓挠癖（Titillomania）：有抓挠自己的强迫倾向。',
  '手术狂（Tomomania）：对实施手术有反常的爱好。',
  '拔毛癖（Trichotillomania）：执着于拔下自己的头发。',
  '臆盲症（Typhlomania）：病理性地认定自己已经失明。',
  '嗜外狂（Xenomania）：痴迷于异国的事物。',
  '喜兽癖（Zoomania）：对待动物的态度近乎疯狂地友善。'
];

module.exports = { TEMP_INSANITY, LONG_INSANITY, FEAR, MANIA };
